<?php require_once 'templates/head.phtml';?>

<div class="flexColumna">
    <?php if ($userRol == 2){ ?>
    <section class="agregar">
        <span class="bg-warning">Editar Producto</span>
        <form action="updateCerveza" method="POST">
            <div class="flexWrap">
                <input type="text" name="id" hidden value="<?php echo $cerveza->id_cerveza?>">
                <input required name="nombre" value="<?php echo $cerveza->nombre ?>">
                <input required type="number" name="IBU" min="1" value="<?php echo $cerveza->IBU?>">
                <input required type="number" name="ALC" min="1" value="<?php echo $cerveza->ALC ?>">
                <select name="id_estilo">
                <?php foreach ($estilos as $estilo): ?>
                    <option value="<?php echo $estilo->id_estilo; ?>" <?php if ($estilo->id_estilo == $cerveza->id_estilo) echo "selected"; ?>><?php echo $estilo->nombre; ?></option>
                <?php endforeach; ?>
                </select>
                <input required type="number" name="stock" value="<?php echo $cerveza->stock ?>" min="1">
                <input required type="text" name="descripcion" value="<?php echo $cerveza->descripcion ?>">
            </div>

            <div class="flexColumna">
                <button type="submit" class="btnVerde" value="Agregar">Guardar</button>
            </div>
        </form>
    </section>
    <?php }?>
<?php require_once 'templates/footer.phtml';?>