<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <base href="<?php echo BASE_URL ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Cerveceria Berlina</title>
        <link rel="icon" src="../images/logopagina.png" alt="logopestaña">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://kit.fontawesome.com/7964d7a07e.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="css/style.css" />
    </head>
<body>
    <header class="header">
        <?php require_once 'templates/nav.phtml';?>
    </header>
    <div class="flexColumna">
