<?php require_once 'templates/head.phtml';?>
<div class="flexColumna">
    <h1>Lista de usuarios</h1>
    <table>
        <thead>
            <tr>
                <th>NOMBRE</th>
                <th>EMAIL</th>
                <th>ROL</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $user): ?>
                <tr>
                    <td><?php echo $user->nombre; ?></td>
                    <td><?php echo $user->email; ?></td>
                    <td>
                        <form action="modifyUserRol/<?php echo $user->id_usuario; ?>" method="POST">
                            <select name="rol">
                                <option value="1" <?php if ($user->rol == '1') echo 'selected'; ?>>Default</option>
                                <option value="2" <?php if ($user->rol == '2') echo 'selected'; ?>>Administrador</option>
                            </select>
                            <input type="submit" value="MODIFICAR" class="btnOrange">
                        </form>
                    </td>
                    <td><a href="deleteUser/<?php echo $user->email; ?>" class="btnRed">ELIMINAR</a></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php require_once 'templates/footer.phtml';?>